import {
  Compass,
  Zap,
  Brain,
  Target,
  Layers,
  Calculator,
  Flame,
  Radio,
  Shuffle,
  Eye,
  Activity,
  Binary,
  GitBranch,
  Scale,
  Sparkles,
  Crown,
  LucideIcon,
} from 'lucide-react';
import { GameId } from '@/store/gameStore';

export interface GameDefinition {
  id: GameId;
  category: 'logic' | 'speed' | 'memory' | 'attention' | 'dual' | 'math';
  badge: string;
  title: string;
  desc: string;
  features: string;
  bonus: string;
  imageUrl: string;
  icon: LucideIcon;
  badgeBg: string;
  badgeText: string;
  accentColor: string;
}

export const ALL_GAMES: GameDefinition[] = [
  // --- SATRANÇ (ÖNE ÇIKAN BİLİŞSEL STRATEJİ) ---
  {
    id: 'chess',
    category: 'logic',
    badge: 'STRATEJİ & TAKTİK',
    title: 'Satranç: Taktik & Bilişsel Hesap',
    desc: 'Büyükusta taktikleri, 1-2 hamlede mat kombinezonları ve çatal-açmaz bulmacalarıyla zihinsel derinlik.',
    features: '8x8 Gerçek Tahta, FIDE Kuralları',
    bonus: 'Büyükusta Skoru ♟️',
    imageUrl: 'https://images.unsplash.com/photo-1529699211952-734e80c4d42b?auto=format&fit=crop&w=600&q=80',
    icon: Crown,
    badgeBg: 'bg-amber-100 border-amber-300',
    badgeText: 'text-amber-800',
    accentColor: '#b45309',
  },

  // --- MANTIK & PROBLEM ÇÖZME ---
  {
    id: 'maze',
    category: 'logic',
    badge: 'MANTIK & ROTA',
    title: 'Neural Maze: Mantık Labirenti',
    desc: 'Labirentte anahtarları topla, lazer kapılarını aç, altınları topla ve sınırlı hamleyle çıkışa ulaş.',
    features: 'Anahtarlar, Portallar, Tuzaklar',
    bonus: '⭐⭐⭐ Puanlama',
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80',
    icon: Compass,
    badgeBg: 'bg-emerald-100 border-emerald-300',
    badgeText: 'text-emerald-800',
    accentColor: '#059669',
  },
  {
    id: 'circuit',
    category: 'logic',
    badge: 'MANTIK & DEVRE',
    title: 'Circuit Flow: Siber Devre',
    desc: 'Devre hatlarını 90 derece döndürerek kesintisiz güç akışını sağla. Uzamsal problem çözme refleksi.',
    features: 'Siber Izgara, Hat Bağlantısı',
    bonus: 'Akış Bonusu ⚡',
    imageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=600&q=80',
    icon: Binary,
    badgeBg: 'bg-cyan-100 border-cyan-300',
    badgeText: 'text-cyan-800',
    accentColor: '#0891b2',
  },
  {
    id: 'tower',
    category: 'logic',
    badge: 'MANTIK & PLANLAMA',
    title: 'Tower of Hanoi: Kule Dengesi',
    desc: 'Halka kulelerini en az hamleyle hedef sütuna taşı. Önleyici planlama ve yürütücü işlev antrenmanı.',
    features: 'Stratejik Hamle, Kural Sınırı',
    bonus: 'Hafif Hamle Rozeti 🏗️',
    imageUrl: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?auto=format&fit=crop&w=600&q=80',
    icon: Layers,
    badgeBg: 'bg-teal-100 border-teal-300',
    badgeText: 'text-teal-800',
    accentColor: '#0d9488',
  },
  {
    id: 'syllogism',
    category: 'logic',
    badge: 'MANTIK & ÇIKARIM',
    title: 'Syllogism: Mantıksal Çıkarım',
    desc: 'Öncül önermeleri analiz ederek sonucun doğru mu yanlış mı olduğunu hızla saptayın.',
    features: 'Dedüktif Mantık, Venn Akıl Yürütme',
    bonus: 'Analitik Puan 💡',
    imageUrl: 'https://images.unsplash.com/photo-1453728013993-6d66e9c9123a?auto=format&fit=crop&w=600&q=80',
    icon: GitBranch,
    badgeBg: 'bg-emerald-100 border-emerald-300',
    badgeText: 'text-emerald-800',
    accentColor: '#059669',
  },

  // --- HIZ & REFLEKS ---
  {
    id: 'shift',
    category: 'speed',
    badge: 'HIZ & REFLEKS',
    title: 'Neural Shift: Kural & Hız',
    desc: 'Sürekli değişen kurallara anında adapte ol, çeldirici yazılara aldanmadan kombo yap.',
    features: 'Kombo Çarpanı, Çeldirici Yazılar',
    bonus: 'Altın Bonusu 🪙',
    imageUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=600&q=80',
    icon: Zap,
    badgeBg: 'bg-purple-100 border-purple-300',
    badgeText: 'text-purple-800',
    accentColor: '#7c3aed',
  },
  {
    id: 'color-rush',
    category: 'speed',
    badge: 'HIZ & STROOP',
    title: 'Color Rush: Renk Çelişkisi',
    desc: 'Klasik Stroop testi! Kelimenin anlamına mı yoksa yazı rengine mi odaklanacağın saniyede bir değişir.',
    features: 'Bilişsel Ketleme, Çeldirici Renkler',
    bonus: 'Refleks Çarpanı 🔥',
    imageUrl: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?auto=format&fit=crop&w=600&q=80',
    icon: Flame,
    badgeBg: 'bg-rose-100 border-rose-300',
    badgeText: 'text-rose-800',
    accentColor: '#e11d48',
  },
  {
    id: 'chrono',
    category: 'speed',
    badge: 'HIZ & ZAMANLAMA',
    title: 'Chrono Tap: Milisaniye Refleksi',
    desc: 'Işık hızında salınan ibreyi yeşil kritik pencereye girdiğinde durdur. Milisaniyelik reaksiyon testi.',
    features: 'Hassas Zamanlama, Daralan Pencere',
    bonus: 'Kritik Vuruş ⏱️',
    imageUrl: 'https://images.unsplash.com/photo-1508057198894-247b23fe5ade?auto=format&fit=crop&w=600&q=80',
    icon: Activity,
    badgeBg: 'bg-violet-100 border-violet-300',
    badgeText: 'text-violet-800',
    accentColor: '#7c3aed',
  },
  {
    id: 'traffic',
    category: 'speed',
    badge: 'HIZ & TERS YÖN',
    title: 'Traffic Control: Yön Refleksi',
    desc: 'Yeşil okta gösterilen yöne, kırmızı okta tam tersi yöne anında bas. Otomatik yön algısını kır.',
    features: 'Yön Çelişkisi, Hızlı Akış',
    bonus: 'Kombo Zinciri 🚦',
    imageUrl: 'https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?auto=format&fit=crop&w=600&q=80',
    icon: Shuffle,
    badgeBg: 'bg-purple-100 border-purple-300',
    badgeText: 'text-purple-800',
    accentColor: '#7c3aed',
  },

  // --- HAFIZA & UZAMSAL BELLEK ---
  {
    id: 'pattern',
    category: 'memory',
    badge: 'HAFIZA & MEKÂN',
    title: 'Pattern Matrix: Hafıza Grid',
    desc: 'Yanan matris desenini aklında tut! Flaş süresi bittiğinde kareleri doğru sırayla eksiksiz işaretle.',
    features: '3x3 - 6x6 Matris, Dinamik Flaş',
    bonus: '3 Can Hakkı ❤️',
    imageUrl: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&w=600&q=80',
    icon: Brain,
    badgeBg: 'bg-sky-100 border-sky-300',
    badgeText: 'text-sky-800',
    accentColor: '#0284c7',
  },
  {
    id: 'sequence',
    category: 'memory',
    badge: 'HAFIZA & RİTİM',
    title: 'Sequence Recall: Nöro-Ritim',
    desc: 'Sesli ve ışıklı 4 renkli ritim sekansını dinle ve ezberle. Her turda genişleyen bellek zincirini tekrarla.',
    features: 'Görsel & İşitsel Kodlama',
    bonus: 'Müzikal Bellek 🎵',
    imageUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=600&q=80',
    icon: Radio,
    badgeBg: 'bg-blue-100 border-blue-300',
    badgeText: 'text-blue-800',
    accentColor: '#2563eb',
  },
  {
    id: 'spatial',
    category: 'memory',
    badge: 'HAFIZA & 3D',
    title: 'Spatial 3D: Zihinsel Döndürme',
    desc: 'İzometrik 3D blok yapılarını zihninde döndür ve sağdaki yapının aynı mı ayna simetrisi mi olduğunu bul.',
    features: 'Shepard-Metzler Rotasyonu',
    bonus: 'Uzamsal IQ 📐',
    imageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80',
    icon: Compass,
    badgeBg: 'bg-sky-100 border-sky-300',
    badgeText: 'text-sky-800',
    accentColor: '#0284c7',
  },
  {
    id: 'word-pair',
    category: 'memory',
    badge: 'HAFIZA & ÇAĞRIŞIM',
    title: 'Word Pairs: Çağrışım Belleği',
    desc: 'Kavram çiftlerini hafızaya kaydet. İpucu kelime verildiğinde eşleşen kavramı anında çağır.',
    features: 'Semantik Eşleşme, Geri Çağırma',
    bonus: 'Sözcük Belleği 📚',
    imageUrl: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&w=600&q=80',
    icon: Sparkles,
    badgeBg: 'bg-cyan-100 border-cyan-300',
    badgeText: 'text-cyan-800',
    accentColor: '#0891b2',
  },

  // --- DİKKAT & ODAKLANMA ---
  {
    id: 'focus',
    category: 'attention',
    badge: 'DİKKAT & ODAK',
    title: 'Focus Flash: Hedef Avcısı',
    desc: 'Çeldirici geometrik şekiller arasından kurala uyan hedefi milisaniyeler içinde yakala ve kombo yap.',
    features: 'Görsel Arama, Zaman Baskısı',
    bonus: '5x Kombo Çarpanı ⚡',
    imageUrl: 'https://images.unsplash.com/photo-1499244571948-7ccddb3583f1?auto=format&fit=crop&w=600&q=80',
    icon: Target,
    badgeBg: 'bg-amber-100 border-amber-300',
    badgeText: 'text-amber-800',
    accentColor: '#d97706',
  },
  {
    id: 'subitizing',
    category: 'attention',
    badge: 'DİKKAT & SEZİ',
    title: 'Subitizing: Hızlı Sayma',
    desc: 'Ekranda 400 milisaniye parlayıp sönen noktaların miktarını tek tek saymadan anında tahmin et.',
    features: 'Görsel Nicelik Sezisi, Anlık Flaş',
    bonus: 'Göz İntuisi 👁️',
    imageUrl: 'https://images.unsplash.com/photo-1516981879613-9f5da904015f?auto=format&fit=crop&w=600&q=80',
    icon: Eye,
    badgeBg: 'bg-amber-100 border-amber-300',
    badgeText: 'text-amber-800',
    accentColor: '#d97706',
  },
  {
    id: 'radar',
    category: 'attention',
    badge: 'DİKKAT & ÇOKLU TAKİP',
    title: 'Radar Tracking: Çoklu Hedef Takibi',
    desc: 'Hedef noktalar işaretlendikten sonra hareket eden diğer noktalarla karışır. Orijinal hedefleri gözünle takip et.',
    features: 'NASA MOT Çoklu Nesne Takibi',
    bonus: 'Göz Çevikliği 📡',
    imageUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=600&q=80',
    icon: Radio,
    badgeBg: 'bg-orange-100 border-orange-300',
    badgeText: 'text-orange-800',
    accentColor: '#ea580c',
  },
  {
    id: 'peripheral',
    category: 'attention',
    badge: 'DİKKAT & ÇEVRESEL',
    title: 'Peripheral Vision: Çevresel Görüş',
    desc: 'Merkezdeki hedefe odaklanırken ekranın uzak köşelerinde beliren hafif titreşimleri çevre vizyonunla yakala.',
    features: 'Genişletilmiş Görsel Alan',
    bonus: 'Panoramik Algı 🔭',
    imageUrl: 'https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?auto=format&fit=crop&w=600&q=80',
    icon: Eye,
    badgeBg: 'bg-amber-100 border-amber-300',
    badgeText: 'text-amber-800',
    accentColor: '#d97706',
  },

  // --- BÖLÜNMÜŞ DİKKAT & BİLİŞSEL ESNEKLİK ---
  {
    id: 'dual',
    category: 'dual',
    badge: 'ESNEKLİK & DUAL',
    title: 'Dual Task: İkili Görev',
    desc: 'Bilimsel Dual N-Back egzersizi! Hem konum hem harf uyaranlarını belleğe alarak eşleşmeleri eşzamanlı çöz.',
    features: 'Dual N-Back, Çalışma Belleği',
    bonus: 'Nöro-Esneklik Puanı 🎯',
    imageUrl: 'https://images.unsplash.com/photo-1507413245164-6160d8298b31?auto=format&fit=crop&w=600&q=80',
    icon: Layers,
    badgeBg: 'bg-rose-100 border-rose-300',
    badgeText: 'text-rose-800',
    accentColor: '#e11d48',
  },
  {
    id: 'switch-task',
    category: 'dual',
    badge: 'ESNEKLİK & GEÇİŞ',
    title: 'Switch Task: Görev Geçişi',
    desc: 'Mavi renkte sayının tek/çiftliğine, turuncu renkte harfin sesli/sessizliğine karar ver. Zihinsel set değiştirme.',
    features: 'Yürütücü İşlev, Zihin Esnekliği',
    bonus: 'Adaptasyon Skoru 🔄',
    imageUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=600&q=80',
    icon: Shuffle,
    badgeBg: 'bg-rose-100 border-rose-300',
    badgeText: 'text-rose-800',
    accentColor: '#e11d48',
  },

  // --- SAYISAL & ANALİTİK ---
  {
    id: 'math',
    category: 'math',
    badge: 'SAYISAL & HIZ',
    title: 'Speed Math: Sayısal Mantık',
    desc: 'Zihinsel aritmetik temposu! Denklemleri ve eksik işlem operatörlerini süre tükenmeden yıldırım gibi yanıtla.',
    features: 'Dinamik Denklemler, Süre Bonusu',
    bonus: '+1.5s Hız Primi ⏱️',
    imageUrl: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?auto=format&fit=crop&w=600&q=80',
    icon: Calculator,
    badgeBg: 'bg-indigo-100 border-indigo-300',
    badgeText: 'text-indigo-800',
    accentColor: '#4f46e5',
  },
  {
    id: 'estimate',
    category: 'math',
    badge: 'SAYISAL & TAHMİN',
    title: 'Magnitude: Büyüklük Sezisi',
    desc: 'Kesirleri, yüzdeleri ve sayısal oranları hesap yapmadan sezgisel olarak karşılaştır. Hangi taraf daha büyük?',
    features: 'Sayısal Sezi, Kesir & Yüzde',
    bonus: 'Matematiksel Algı ⚖️',
    imageUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=600&q=80',
    icon: Scale,
    badgeBg: 'bg-indigo-100 border-indigo-300',
    badgeText: 'text-indigo-800',
    accentColor: '#4f46e5',
  },
];
